--[[
    Hydra Inventory - Item Registry

    Add items here. Each item needs at minimum: name, label, weight.
    The system auto-indexes by name for O(1) lookup.

    Categories: general, consumable, weapon, ammo, tool, material,
                clothing, electronic, document, drug, key, misc

    Consumable format:
        consumable = {
            status = { hunger = 20, thirst = 10 },  -- hydra_status effects
            anim = { dict = '...', clip = '...' },   -- optional override
            prop = { model = '...', bone = 57005 },  -- optional hand prop
            duration = 5000,                          -- consume time ms
            effects = { armour = 5 },                 -- special effects
            sound = 'eat',                            -- optional sound
        }
]]

HydraConfig = HydraConfig or {}

HydraConfig.Items = {
    -- ===================================================================
    -- MONEY
    -- ===================================================================
    {
        name = 'cash',
        label = 'Cash',
        weight = 0,
        stackable = true,
        maxStack = 999999,
        description = 'Physical cash money',
        category = 'general',
        image = 'cash.png',
        unique = false,
        useable = false,
    },

    -- ===================================================================
    -- FOOD & DRINK (consumables)
    -- ===================================================================
    {
        name = 'burger',
        label = 'Burger',
        weight = 300,
        stackable = true,
        maxStack = 10,
        description = 'A juicy burger that satisfies hunger',
        category = 'consumable',
        image = 'burger.png',
        useable = true,
        consumable = {
            status = { hunger = 30 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = 'prop_cs_burger_01', bone = 18905, offset = vec3(0.13, 0.05, 0.02), rotation = vec3(-50.0, 16.0, 60.0) },
            duration = 5000,
        },
    },
    {
        name = 'pizza',
        label = 'Pizza Slice',
        weight = 350,
        stackable = true,
        maxStack = 10,
        description = 'A delicious slice of pizza',
        category = 'consumable',
        image = 'pizza.png',
        useable = true,
        consumable = {
            status = { hunger = 35 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            duration = 5000,
        },
    },
    {
        name = 'sandwich',
        label = 'Sandwich',
        weight = 250,
        stackable = true,
        maxStack = 10,
        description = 'A fresh sandwich',
        category = 'consumable',
        image = 'sandwich.png',
        useable = true,
        consumable = {
            status = { hunger = 25 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            duration = 4000,
        },
    },
    {
        name = 'chips',
        label = 'Chips',
        weight = 100,
        stackable = true,
        maxStack = 20,
        description = 'A bag of salty chips',
        category = 'consumable',
        image = 'chips.png',
        useable = true,
        consumable = {
            status = { hunger = 10, thirst = -5 },
            duration = 3000,
        },
    },
    {
        name = 'donut',
        label = 'Donut',
        weight = 150,
        stackable = true,
        maxStack = 12,
        description = 'A sweet glazed donut',
        category = 'consumable',
        image = 'donut.png',
        useable = true,
        consumable = {
            status = { hunger = 15, stress = -5 },
            duration = 3000,
        },
    },
    {
        name = 'water',
        label = 'Water Bottle',
        weight = 500,
        stackable = true,
        maxStack = 20,
        description = 'A refreshing bottle of water',
        category = 'consumable',
        image = 'water.png',
        useable = true,
        consumable = {
            status = { thirst = 35 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = 'prop_ld_flow_bottle', bone = 18905, offset = vec3(0.01, 0.01, -0.06), rotation = vec3(0.0, 0.0, 0.0) },
            duration = 4000,
        },
    },
    {
        name = 'cola',
        label = 'eCola',
        weight = 400,
        stackable = true,
        maxStack = 20,
        description = 'A can of eCola',
        category = 'consumable',
        image = 'cola.png',
        useable = true,
        consumable = {
            status = { thirst = 25, hunger = 5 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = 'prop_ecola_can', bone = 18905 },
            duration = 3000,
        },
    },
    {
        name = 'sprunk',
        label = 'Sprunk',
        weight = 400,
        stackable = true,
        maxStack = 20,
        description = 'A can of Sprunk',
        category = 'consumable',
        image = 'sprunk.png',
        useable = true,
        consumable = {
            status = { thirst = 25, hunger = 5 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = 'ng_proc_sodacan_01a', bone = 18905 },
            duration = 3000,
        },
    },
    {
        name = 'coffee',
        label = 'Coffee',
        weight = 300,
        stackable = true,
        maxStack = 10,
        description = 'A hot cup of coffee',
        category = 'consumable',
        image = 'coffee.png',
        useable = true,
        consumable = {
            status = { thirst = 20, stress = -10 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = 'p_amb_coffeecup_01', bone = 18905 },
            duration = 4000,
        },
    },
    {
        name = 'energy_drink',
        label = 'Energy Drink',
        weight = 350,
        stackable = true,
        maxStack = 10,
        description = 'Boosts your energy and reduces stress',
        category = 'consumable',
        image = 'energy_drink.png',
        useable = true,
        consumable = {
            status = { thirst = 15, stress = -20 },
            effects = { stamina = 30 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            duration = 3000,
        },
    },
    {
        name = 'beer',
        label = 'Beer',
        weight = 400,
        stackable = true,
        maxStack = 12,
        description = 'A cold beer',
        category = 'consumable',
        image = 'beer.png',
        useable = true,
        consumable = {
            status = { thirst = 20, stress = -15 },
            effects = { drunk = 15 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = 'prop_amb_beer_bottle', bone = 18905 },
            duration = 4000,
        },
    },
    {
        name = 'whiskey',
        label = 'Whiskey',
        weight = 500,
        stackable = true,
        maxStack = 5,
        description = 'A bottle of fine whiskey',
        category = 'consumable',
        image = 'whiskey.png',
        useable = true,
        consumable = {
            status = { thirst = 10, stress = -30 },
            effects = { drunk = 40 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            duration = 5000,
        },
    },

    -- ===================================================================
    -- MEDICAL
    -- ===================================================================
    {
        name = 'bandage',
        label = 'Bandage',
        weight = 100,
        stackable = true,
        maxStack = 20,
        description = 'A basic bandage for small wounds',
        category = 'consumable',
        image = 'bandage.png',
        useable = true,
        consumable = {
            effects = { heal = 15 },
            anim = { dict = 'anim@heists@narcotics@funding@gang_idle', clip = 'gang_idle_tablet' },
            duration = 4000,
        },
    },
    {
        name = 'firstaid',
        label = 'First Aid Kit',
        weight = 500,
        stackable = true,
        maxStack = 5,
        description = 'A comprehensive first aid kit',
        category = 'consumable',
        image = 'firstaid.png',
        useable = true,
        consumable = {
            effects = { heal = 50 },
            anim = { dict = 'anim@heists@narcotics@funding@gang_idle', clip = 'gang_idle_tablet' },
            duration = 8000,
        },
    },
    {
        name = 'painkillers',
        label = 'Painkillers',
        weight = 50,
        stackable = true,
        maxStack = 30,
        description = 'Over-the-counter painkillers',
        category = 'consumable',
        image = 'painkillers.png',
        useable = true,
        consumable = {
            effects = { heal = 10, armour = 5 },
            status = { stress = -15 },
            duration = 3000,
        },
    },
    {
        name = 'armour_vest',
        label = 'Body Armour',
        weight = 3000,
        stackable = false,
        maxStack = 1,
        description = 'A protective body armour vest',
        category = 'general',
        image = 'armour.png',
        useable = true,
        consumable = {
            effects = { armour = 100 },
            duration = 5000,
        },
    },

    -- ===================================================================
    -- TOOLS
    -- ===================================================================
    {
        name = 'phone',
        label = 'Phone',
        weight = 200,
        stackable = false,
        maxStack = 1,
        description = 'A smartphone',
        category = 'electronic',
        image = 'phone.png',
        useable = true,
        unique = true,
    },
    {
        name = 'radio',
        label = 'Radio',
        weight = 500,
        stackable = false,
        maxStack = 1,
        description = 'A portable radio for communication',
        category = 'electronic',
        image = 'radio.png',
        useable = true,
    },
    {
        name = 'lockpick',
        label = 'Lockpick',
        weight = 100,
        stackable = true,
        maxStack = 10,
        description = 'A basic lockpick set',
        category = 'tool',
        image = 'lockpick.png',
        useable = true,
    },
    {
        name = 'repairkit',
        label = 'Repair Kit',
        weight = 2500,
        stackable = true,
        maxStack = 3,
        description = 'A vehicle repair kit',
        category = 'tool',
        image = 'repairkit.png',
        useable = true,
    },
    {
        name = 'advancedrepairkit',
        label = 'Advanced Repair Kit',
        weight = 4000,
        stackable = true,
        maxStack = 2,
        description = 'An advanced vehicle repair kit for full restoration',
        category = 'tool',
        image = 'advancedrepairkit.png',
        useable = true,
    },
    {
        name = 'jerry_can',
        label = 'Jerry Can',
        weight = 5000,
        stackable = true,
        maxStack = 3,
        description = 'A fuel container',
        category = 'tool',
        image = 'jerrycan.png',
        useable = true,
    },
    {
        name = 'binoculars',
        label = 'Binoculars',
        weight = 800,
        stackable = false,
        maxStack = 1,
        description = 'See things from far away',
        category = 'tool',
        image = 'binoculars.png',
        useable = true,
    },
    {
        name = 'camera',
        label = 'Camera',
        weight = 600,
        stackable = false,
        maxStack = 1,
        description = 'A digital camera',
        category = 'electronic',
        image = 'camera.png',
        useable = true,
    },
    {
        name = 'flashlight',
        label = 'Flashlight',
        weight = 300,
        stackable = false,
        maxStack = 1,
        description = 'A portable flashlight',
        category = 'tool',
        image = 'flashlight.png',
        useable = true,
    },

    -- ===================================================================
    -- MATERIALS / CRAFTING
    -- ===================================================================
    {
        name = 'plastic',
        label = 'Plastic',
        weight = 100,
        stackable = true,
        maxStack = 50,
        description = 'Scrap plastic material',
        category = 'material',
        image = 'plastic.png',
    },
    {
        name = 'paper',
        label = 'Paper',
        weight = 50,
        stackable = true,
        maxStack = 100,
        description = 'Sheets of paper',
        category = 'material',
        image = 'paper.png',
    },
    {
        name = 'bottle',
        label = 'Empty Bottle',
        weight = 100,
        stackable = true,
        maxStack = 30,
        description = 'An empty glass bottle',
        category = 'material',
        image = 'bottle.png',
    },
    {
        name = 'lighter',
        label = 'Lighter',
        weight = 50,
        stackable = true,
        maxStack = 5,
        description = 'A disposable lighter',
        category = 'tool',
        image = 'lighter.png',
        useable = true,
    },
    {
        name = 'phone_scrap',
        label = 'Phone Scrap',
        weight = 150,
        stackable = true,
        maxStack = 20,
        description = 'Electronic components from a broken phone',
        category = 'material',
        image = 'phone_scrap.png',
    },
    {
        name = 'metalscrap',
        label = 'Metal Scrap',
        weight = 300,
        stackable = true,
        maxStack = 50,
        description = 'Scrap metal pieces',
        category = 'material',
        image = 'metalscrap.png',
    },
    {
        name = 'copper',
        label = 'Copper Wire',
        weight = 200,
        stackable = true,
        maxStack = 50,
        description = 'Strands of copper wire',
        category = 'material',
        image = 'copper.png',
    },
    {
        name = 'rubber',
        label = 'Rubber',
        weight = 150,
        stackable = true,
        maxStack = 50,
        description = 'Rubber material',
        category = 'material',
        image = 'rubber.png',
    },
    {
        name = 'glass',
        label = 'Glass Shard',
        weight = 100,
        stackable = true,
        maxStack = 50,
        description = 'A shard of glass',
        category = 'material',
        image = 'glass.png',
    },
    {
        name = 'fabric',
        label = 'Fabric',
        weight = 100,
        stackable = true,
        maxStack = 50,
        description = 'Cloth fabric material',
        category = 'material',
        image = 'fabric.png',
    },

    -- ===================================================================
    -- DOCUMENTS / KEYS
    -- ===================================================================
    {
        name = 'id_card',
        label = 'ID Card',
        weight = 10,
        stackable = false,
        maxStack = 1,
        description = 'Government-issued identification',
        category = 'document',
        image = 'id_card.png',
        useable = true,
        unique = true,
    },
    {
        name = 'drivers_license',
        label = "Driver's License",
        weight = 10,
        stackable = false,
        maxStack = 1,
        description = 'A valid driving license',
        category = 'document',
        image = 'drivers_license.png',
        useable = true,
        unique = true,
    },
    {
        name = 'weapon_license',
        label = 'Weapon License',
        weight = 10,
        stackable = false,
        maxStack = 1,
        description = 'A firearms license',
        category = 'document',
        image = 'weapon_license.png',
        useable = true,
        unique = true,
    },
    {
        name = 'house_key',
        label = 'House Key',
        weight = 50,
        stackable = false,
        maxStack = 1,
        description = 'A key to a property',
        category = 'key',
        image = 'house_key.png',
        useable = true,
        unique = true,
    },
    {
        name = 'vehicle_key',
        label = 'Vehicle Key',
        weight = 50,
        stackable = false,
        maxStack = 1,
        description = 'A vehicle key',
        category = 'key',
        image = 'vehicle_key.png',
        useable = true,
        unique = true,
    },

    -- ===================================================================
    -- MISC
    -- ===================================================================
    {
        name = 'backpack_small',
        label = 'Small Backpack',
        weight = 1000,
        stackable = false,
        maxStack = 1,
        description = 'Increases carry capacity by 20kg',
        category = 'general',
        image = 'backpack_small.png',
        useable = true,
        backpack = { extraWeight = 20000, extraSlots = 5 },
    },
    {
        name = 'backpack_large',
        label = 'Large Backpack',
        weight = 2000,
        stackable = false,
        maxStack = 1,
        description = 'Increases carry capacity by 50kg',
        category = 'general',
        image = 'backpack_large.png',
        useable = true,
        backpack = { extraWeight = 50000, extraSlots = 10 },
    },
    {
        name = 'wallet',
        label = 'Wallet',
        weight = 100,
        stackable = false,
        maxStack = 1,
        description = 'A leather wallet',
        category = 'general',
        image = 'wallet.png',
        useable = true,
    },
    {
        name = 'watch',
        label = 'Watch',
        weight = 150,
        stackable = false,
        maxStack = 1,
        description = 'A wristwatch',
        category = 'general',
        image = 'watch.png',
        useable = true,
    },
    {
        name = 'cigarette',
        label = 'Cigarette',
        weight = 10,
        stackable = true,
        maxStack = 20,
        description = 'A cigarette',
        category = 'consumable',
        image = 'cigarette.png',
        useable = true,
        consumable = {
            status = { stress = -15 },
            anim = { dict = 'amb@world_human_smoking@male@male_a@enter', clip = 'enter' },
            prop = { model = 'prop_cs_ciggy_01', bone = 47419 },
            duration = 10000,
        },
    },
    {
        name = 'joint',
        label = 'Joint',
        weight = 20,
        stackable = true,
        maxStack = 10,
        description = 'A rolled joint',
        category = 'drug',
        image = 'joint.png',
        useable = true,
        consumable = {
            status = { stress = -40 },
            effects = { screen_effect = 'DrugsMichaelAliensFight', duration = 30000 },
            anim = { dict = 'amb@world_human_smoking_pot@male@idle_a', clip = 'idle_a' },
            prop = { model = 'prop_sh_joint_01', bone = 47419 },
            duration = 12000,
        },
    },
}
